export default {
   GET_PROFILE_INFO:'GET_PROFILE_INFO',
   UPDATE_USER_IMG:'UPDATE_USER_IMG',
   UPDATE_USER_NAME:'UPDATE_USER_NAME',
   UPDATE_USER_PHONE:'UPDATE_USER_PHONE',

   GET_ADDRESS_LIST:'GET_ADDRESS_LIST',
   ADD_OR_UPDATE_ADDRESS:'ADD_OR_UPDATE_ADDRESS',
   SET_MY_COUPONS:'SET_MY_COUPONS',
   GET_ORDER_DETAILS:'GET_ORDER_DETAILS',
   SET_EXPRESS_INFO:'SET_EXPRESS_INFO',
   CLEAR_ME_DATA:'CLEAR_ME_DATA'
}
