export default {
    GET_DISEASE_TYPES:'GET_DISEASE_TYPES', //获取疾病分类列表
    GET_QUESTION_LIST:'GET_QUESTION_LIST',
    SET_USER_ANSWER:'SET_USER_ANSWER',
    SET_ANSWER_RESULT:'SET_ANSWER_RESULT',
    SET_CONFIRM_ORDER_INFO:'SET_CONFIRM_ORDER_INFO',
    GET_ORDER_INFO:'GET_ORDER_INFO',
    COMPUTE_ORDER_MONEY:'COMPUTE_ORDER_MONEY',
    CLEAR_HOME_DATA:'CLEAR_HOME_DATA'
}
